---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml

vars:
  - fieldref:
      fieldPath: metadata.namespace
    name: SUBMARINER_OPERATOR_NAMESPACE
    objref:
      group: apps
      kind: Deployment
      name: submariner-operator
      version: v1

patches:
  - path: patches/related-images.deployment.config.yaml
    target:
      group: apps
      kind: Deployment
      name: submariner-operator
      namespace: system
      version: v1
