apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: submariner-operator:lighthouse
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - lighthouse.submariner.io
    resources:
      - '*'
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
