apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: submariner-routeagent
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - endpoints
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resourceNames:
  - ovn-cert
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - config.openshift.io
  resourceNames:
  - cluster
  resources:
  - networks
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - projectcalico.org
  resources:
  - ippools
  verbs:
  - get
  - create
  - delete
  - update
  - deletecollection
- apiGroups:
  - operator.tigera.io
  resources:
  - installations
  verbs:
  - get
  - update
