apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  creationTimestamp: null
  name: submariner-gateway
secrets:
- name: submariner-broker-secret
- name: submariner-ipsec-psk
