apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: submariner-lighthouse-coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-lighthouse-coredns
subjects:
- kind: ServiceAccount
  name: submariner-lighthouse-coredns
  namespace: submariner-operator
