apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: submariner-lighthouse-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-lighthouse-agent
subjects:
- kind: ServiceAccount
  name: submariner-lighthouse-agent
  namespace: submariner-operator
