---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: submariner-lighthouse-coredns
subjects:
  - kind: ServiceAccount
    name: submariner-lighthouse-coredns
roleRef:
  kind: Role
  name: submariner-lighthouse-coredns
  apiGroup: rbac.authorization.k8s.io
