---
name: Reporting

on:
  push:
    branches:
      - devel
      - release-*

permissions: {}

jobs:
  unit-coverage:
    name: Go Unit Test Coverage
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Run Go unit tests
        run: make unit

      - name: Run SonarScan, upload Go test results and coverage
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  variant-analysis:
    name: Variant Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Initialize CodeQL
        uses: github/codeql-action/init@3599b3baa15b485a2e49ef411a7a4bb2452e7f93
        with:
          languages: go
      - name: Run CodeQL variant analysis
        uses: github/codeql-action/analyze@3599b3baa15b485a2e49ef411a7a4bb2452e7f93
      - name: Show CodeQL scan SARIF report
        if: always()
        run: cat ../results/go.sarif

  vulnerability-scan:
    name: Vulnerability Scanning
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Run Anchore vulnerability scanner
        uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8
        id: scan
        with:
          path: "."
          fail-build: false
      - name: Show Anchore scan SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
