---
name: Unit Tests

on:
  pull_request:
  push:
    tags:
      - 'v**'

permissions: {}

jobs:
  unit-testing:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Run Go unit tests
        run: |
          set -o pipefail
          make unit 2>&1 | tee artifacts/unittest.log

      - name: Collect artifacts
        run: |
          for f in $(find ./pkg -name "*.xml"); do
            mkdir -p artifacts/$(dirname $f)
            cp $f -rfp artifacts/$f
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: Unit test artifacts
          path: artifacts
